
package com.carddex.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "Carddex_Make", targetNamespace = "Carddex_Make", wsdlLocation = "http://172.16.3.15/carddex_up/ws/carddex_make?WSDL")
public class CarddexMake
    extends Service
{

    private final static URL CARDDEXMAKE_WSDL_LOCATION;
    private final static WebServiceException CARDDEXMAKE_EXCEPTION;
    private final static QName CARDDEXMAKE_QNAME = new QName("Carddex_Make", "Carddex_Make");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://172.16.3.15/carddex_up/ws/carddex_make?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARDDEXMAKE_WSDL_LOCATION = url;
        CARDDEXMAKE_EXCEPTION = e;
    }

    public CarddexMake() {
        super(__getWsdlLocation(), CARDDEXMAKE_QNAME);
    }

    public CarddexMake(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARDDEXMAKE_QNAME, features);
    }

    public CarddexMake(URL wsdlLocation) {
        super(wsdlLocation, CARDDEXMAKE_QNAME);
    }

    public CarddexMake(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARDDEXMAKE_QNAME, features);
    }

    public CarddexMake(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarddexMake(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarddexMakePortType
     */
    @WebEndpoint(name = "Carddex_MakeSoap")
    public CarddexMakePortType getCarddexMakeSoap() {
        return super.getPort(new QName("Carddex_Make", "Carddex_MakeSoap"), CarddexMakePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarddexMakePortType
     */
    @WebEndpoint(name = "Carddex_MakeSoap")
    public CarddexMakePortType getCarddexMakeSoap(WebServiceFeature... features) {
        return super.getPort(new QName("Carddex_Make", "Carddex_MakeSoap"), CarddexMakePortType.class, features);
    }

    /**
     * 
     * @return
     *     returns CarddexMakePortType
     */
    @WebEndpoint(name = "Carddex_MakeSoap12")
    public CarddexMakePortType getCarddexMakeSoap12() {
        return super.getPort(new QName("Carddex_Make", "Carddex_MakeSoap12"), CarddexMakePortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarddexMakePortType
     */
    @WebEndpoint(name = "Carddex_MakeSoap12")
    public CarddexMakePortType getCarddexMakeSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("Carddex_Make", "Carddex_MakeSoap12"), CarddexMakePortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARDDEXMAKE_EXCEPTION!= null) {
            throw CARDDEXMAKE_EXCEPTION;
        }
        return CARDDEXMAKE_WSDL_LOCATION;
    }

}
