
package com.carddex.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6-1b01 
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Carddex_MakePortType", targetNamespace = "Carddex_Make")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarddexMakePortType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetList", action = "Carddex_Make#Carddex_Make:GetList")
    @WebResult(targetNamespace = "Carddex_Make")
    @RequestWrapper(localName = "GetList", targetNamespace = "Carddex_Make", className = "com.carddex.ws.GetList")
    @ResponseWrapper(localName = "GetListResponse", targetNamespace = "Carddex_Make", className = "com.carddex.ws.GetListResponse")
    public String getList();

    /**
     * 
     * @param data
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Test", action = "Carddex_Make#Carddex_Make:Test")
    @WebResult(targetNamespace = "Carddex_Make")
    @RequestWrapper(localName = "Test", targetNamespace = "Carddex_Make", className = "com.carddex.ws.Test")
    @ResponseWrapper(localName = "TestResponse", targetNamespace = "Carddex_Make", className = "com.carddex.ws.TestResponse")
    public String test(
        @WebParam(name = "Data", targetNamespace = "Carddex_Make")
        String data);

    /**
     * 
     * @param number
     * @param year
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInfo", action = "Carddex_Make#Carddex_Make:GetInfo")
    @WebResult(targetNamespace = "Carddex_Make")
    @RequestWrapper(localName = "GetInfo", targetNamespace = "Carddex_Make", className = "com.carddex.ws.GetInfo")
    @ResponseWrapper(localName = "GetInfoResponse", targetNamespace = "Carddex_Make", className = "com.carddex.ws.GetInfoResponse")
    public String getInfo(
        @WebParam(name = "number", targetNamespace = "Carddex_Make")
        String number,
        @WebParam(name = "year", targetNamespace = "Carddex_Make")
        int year);

    /**
     * 
     * @param textQuery
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "ExecuteQuery", action = "Carddex_Make#Carddex_Make:ExecuteQuery")
    @WebResult(targetNamespace = "Carddex_Make")
    @RequestWrapper(localName = "ExecuteQuery", targetNamespace = "Carddex_Make", className = "com.carddex.ws.ExecuteQuery")
    @ResponseWrapper(localName = "ExecuteQueryResponse", targetNamespace = "Carddex_Make", className = "com.carddex.ws.ExecuteQueryResponse")
    public String executeQuery(
        @WebParam(name = "TextQuery", targetNamespace = "Carddex_Make")
        String textQuery);

}
